### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by powerkor** [kamcknig/pick-up-stix#144] opened 2020-10-11 18:43 UTC
I saw you said that it was causing some core db files to become bloated

Even if I disable the plugin would the problem persist? Is it fixed? How do I know if I have this issue and will just updating it fix it?

**Comment by kamcknig** [comment] 2020-10-11 18:59
You can see the issue by opening looking at the scenes.db file in the worlds folder where you have Foundry data stored and taking a token and moving it around the map with the arrow keys. jsts move it a bunch and you'll see the scene db size go up.

It's not a bug or a memory leak. It's the way in which the DB that Foundry uses works. I store data on flags on tokens, and on each update the data gets written over and over and later on gets compacted. But if you have lots of my tokens then it's a lot of data. So it happens even if you don't use my module, it just happens a lot faster because of my module.

**Comment by powerkor** [comment] 2020-10-11 19:41
It has to keep writing data? That’s confusing to me

**Comment by kamcknig** [comment] 2020-10-11 19:53
When you update a DB such as by moving a token you are updating the scenes.db then an entire copy of the scene is requested to be written to the scene DB, then you move the token again and the same thing happens, an entire copy is requested to be written. So your DB file has entire copies of the scene data. Then later the DB compacts all those writes into a single write, merging everything together. 

You can see it  if you open the db file in a text editor and move a toekn twice. you'll see the last two lines that get added to the file are the entire scene data, only with the token x/y updated. but the entire scene still gets written as an update. then the db should later go and clean it up. However, with my toekns and all that data it gets messy, filled up quickly, and i think the db ends up having trouble compacting it at some point

**Closed** 2020-10-25 14:56 UTC
